services:
  moviesphere:
    image: moviesphere
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=#VERY_4ccur4t3_PASSWORD%
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"